"""
Train a BPNet model for one experiment/fold.

Reads experiment paths from configs/experiment_config.yaml and chromosome
splits from configs/chrom_splits.yaml. Fold i holds out fold i for testing
and validates on fold (i+1) % n_folds. Remaining folds are used for training.

For species with too few chromosomes for chromosome-based CV (e.g. S. pombe),
random peak-based splits are used instead when a file matching
configs/splits/{species}_random_fold_assignments.csv exists. That file is
generated by src/data_preprocessing/make_pombe_random_splits.py.

Usage:
    python src/bpnet/fit/fit_bpnet.py -e D.melanogaster-S2_PROcap -f 0
    python src/bpnet/fit/fit_bpnet.py -e S.cerevisiae_PROcap -f 0
    python src/bpnet/fit/fit_bpnet.py -e S.pombe_PROcap -f 0
"""

# Script to fit old Batchnormed BPNet/CLIPNET at https://github.com/adamyhe/csRNANet/blob/2590f0a579afc037e7786d67c69b347eeb302440/src/bpnet/fit/fit.py

import argparse
import sys
from pathlib import Path

import pandas as pd
import torch
import yaml
from bpnetlite import BPNet
from bpnetlite.io import PeakNegativeSampler
from tangermeme.io import extract_loci
from torch.optim import AdamW

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
CONFIG_PATH = REPO_ROOT / "configs" / "experiment_config.yaml"
CHROM_SPLITS_PATH = REPO_ROOT / "configs" / "chrom_splits.yaml"
RANDOM_SPLITS_DIR = REPO_ROOT / "configs" / "splits"


def load_chrom_splits(species: str):
    with open(CHROM_SPLITS_PATH) as f:
        data = yaml.safe_load(f)
    return {int(k): v for k, v in data[species].items()}


def load_bed(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        sep="\t",
        usecols=[0, 1, 2],
        header=None,
        index_col=False,
        names=["chrom", "start", "end"],
    )
    df["chrom"] = df["chrom"].astype(str)
    return df


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "-e",
        "--experiment",
        type=str,
        required=True,
        help="experiment ID as it appears in experiment_config.yaml",
    )
    parser.add_argument(
        "-f",
        "--fold",
        type=int,
        required=True,
        help="fold to hold out for testing (validation = (fold+1) %% n_folds)",
    )
    parser.add_argument(
        "--controls",
        action="store_true",
        help="train with sRNA-seq bias controls (requires pl_control/mn_control in "
        "experiment config); saves to a separate {experiment}_ctl model directory",
    )
    parser.add_argument("-o", "--output-dir", type=str, default=None)
    parser.add_argument("--n-filters", type=int, default=None)
    parser.add_argument("--n-layers", type=int, default=None)
    parser.add_argument("--alpha", type=float, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--max-epochs", type=int, default=None)
    parser.add_argument("--early-stopping", type=int, default=None)
    parser.add_argument("--max-jitter", type=int, default=None)
    parser.add_argument("--random-state", type=int, default=None)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    # Load experiment config
    with open(CONFIG_PATH) as f:
        config = yaml.safe_load(f)

    experiments = config["experiments"]
    if args.experiment not in experiments:
        print(f"Error: {args.experiment} not found in config", file=sys.stderr)
        sys.exit(1)

    exp = experiments[args.experiment]
    processed = exp.get("processed", {})

    peaks_path = str(REPO_ROOT / processed["peaks"])
    pl_bw_path = str(REPO_ROOT / processed["pl_bigwig"])
    mn_bw_path = str(REPO_ROOT / processed["mn_bigwig"])
    sequences_path = str(REPO_ROOT / processed["sequences"])

    # Resolve control paths when --controls is requested
    if args.controls:
        if "pl_control" not in processed or "mn_control" not in processed:
            print(
                f"Error: --controls requested but {args.experiment} has no "
                "pl_control/mn_control in experiment_config.yaml",
                file=sys.stderr,
            )
            sys.exit(1)
        control_paths = [
            str(REPO_ROOT / processed["pl_control"]),
            str(REPO_ROOT / processed["mn_control"]),
        ]
    else:
        control_paths = None

    # Validate data paths
    for path, label in [
        (peaks_path, "peaks"),
        (pl_bw_path, "plus bigwig"),
        (mn_bw_path, "minus bigwig"),
    ]:
        if not Path(path).exists():
            print(f"Error: {label} not found: {path}", file=sys.stderr)
            sys.exit(1)

    gc_negatives_path = str(REPO_ROOT / processed["gc_negatives"])

    # Splits: random peak-based (if assignments file exists) or chromosome-based
    species = exp["species"]
    random_splits_csv = RANDOM_SPLITS_DIR / f"{species}_random_fold_assignments.csv"
    use_random_splits = random_splits_csv.exists()
    if species == "S.pombe" and not use_random_splits:
        print(
            "Error: S. pombe requires random peak-level splits. Generate "
            f"{random_splits_csv} with "
            "src/data_preprocessing/make_pombe_random_splits.py before training.",
            file=sys.stderr,
        )
        sys.exit(1)

    if use_random_splits:
        fold_df = pd.read_csv(random_splits_csv, dtype={"chrom": str})
        n_folds = fold_df["fold"].nunique()
        test_fold = args.fold
        valid_fold = (args.fold + 1) % n_folds
        train_folds = [f for f in range(n_folds) if f not in (test_fold, valid_fold)]
        train_chroms = None
        valid_chroms = None
    else:
        chrom_splits = load_chrom_splits(species)
        n_folds = len(chrom_splits)
        test_fold = args.fold
        valid_fold = (args.fold + 1) % n_folds
        train_folds = [f for f in range(n_folds) if f not in (test_fold, valid_fold)]
        test_chroms = [str(c) for c in chrom_splits[test_fold]]
        valid_chroms = [str(c) for c in chrom_splits[valid_fold]]
        train_chroms = [str(c) for f in train_folds for c in chrom_splits[f]]

    # Output directory
    dir_name = f"{args.experiment}_ctl" if args.controls else args.experiment
    default_dir = REPO_ROOT / "models" / "bpnet" / dir_name
    output_dir = Path(args.output_dir or str(default_dir))
    output_dir.mkdir(parents=True, exist_ok=True)

    # Set defaults
    params = {
        "name": str(output_dir / f"{args.experiment}.fold{args.fold}"),
        "sequences": sequences_path,
        "signals": [pl_bw_path, mn_bw_path],
        "controls": control_paths,
        "loci": peaks_path,
        "in_window": 2114,
        "out_window": 1000,
        "max_jitter": 200,
        "n_filters": 512,
        "n_layers": 8,
        "alpha": 100,
        "reverse_complement": True,
        "batch_size": 64,
        "learning_rate": 0.0005,
        "max_epochs": 100,
        "early_stopping": 20,
        "training_chroms": train_chroms,
        "validation_chroms": valid_chroms,
        "negatives_ratio": 1 / 7,
        "random_state": None,
        "verbose": False,
    }

    # Load peaks and negatives here so we can pre-filter by fold if needed
    peaks = load_bed(params["loci"])
    negatives = load_bed(gc_negatives_path)

    if use_random_splits:
        fold_df["chrom"] = fold_df["chrom"].astype(str)
        merged = peaks.merge(fold_df, on=["chrom", "start", "end"], how="left")
        params["training_loci"] = merged[merged["fold"].isin(train_folds)][
            ["chrom", "start", "end"]
        ].reset_index(drop=True)
        params["validation_loci"] = merged[merged["fold"] == valid_fold][
            ["chrom", "start", "end"]
        ].reset_index(drop=True)
    else:
        params["training_loci"] = peaks
        params["validation_loci"] = peaks

    cli_overrides = {
        "n_filters": args.n_filters,
        "n_layers": args.n_layers,
        "alpha": args.alpha,
        "batch_size": args.batch_size,
        "learning_rate": args.lr,
        "max_epochs": args.max_epochs,
        "early_stopping": args.early_stopping,
        "max_jitter": args.max_jitter,
        "random_state": args.random_state,
    }
    for k, v in cli_overrides.items():
        if v is not None:
            params[k] = v
    if args.verbose:
        params["verbose"] = True

    print(f"Experiment: {args.experiment} ({exp['biosample']})")
    if use_random_splits:
        n_train = len(params["training_loci"])
        n_val = len(params["validation_loci"])
        n_test = (fold_df["fold"] == test_fold).sum()
        print(
            f"Fold {args.fold} (random splits): train={n_train}, "
            f"val={n_val}, test={n_test} peaks"
        )
    else:
        print(f"Fold {args.fold}: test={test_chroms}, valid={valid_chroms}")

    # Extract training loci
    print("Loading training data...")
    print(params["training_loci"].shape)
    print(params["training_chroms"])
    X_peaks = extract_loci(
        loci=params["training_loci"],
        sequences=params["sequences"],
        signals=params["signals"],
        in_signals=params["controls"],
        chroms=params["training_chroms"],
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=params["max_jitter"],
        ignore=list("QWERYUIOPSDFHJKLZXVBNM"),
        return_mask=True,
        verbose=params["verbose"],
    )

    # Filter outlier peaks (top 1% by total signal)
    loci_counts = torch.abs(X_peaks[1]).sum(dim=(1, 2))
    outlier_threshold = torch.quantile(loci_counts, 0.99) * 1.2
    outlier_idxs = loci_counts > outlier_threshold

    X_bg = extract_loci(
        loci=negatives,
        sequences=params["sequences"],
        signals=params["signals"],
        in_signals=params["controls"],
        chroms=params["training_chroms"],  # None for random splits (use all negatives)
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=0,
        ignore=list("QWERYUIOPSDFHJKLZXVBNM"),
        return_mask=True,
        verbose=params["verbose"],
    )

    train_dataset = PeakNegativeSampler(
        peak_sequences=X_peaks[0][~outlier_idxs],
        peak_signals=torch.abs(X_peaks[1][~outlier_idxs]),
        peak_controls=None
        if params["controls"] is None
        else torch.abs(X_peaks[2][~outlier_idxs]),
        negative_sequences=X_bg[0],
        negative_signals=torch.abs(X_bg[1]),
        negative_controls=None if params["controls"] is None else torch.abs(X_bg[2]),
        negative_ratio=params["negatives_ratio"],
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=params["max_jitter"],
        reverse_complement=params["reverse_complement"],
        shuffle=True,
        random_state=params["random_state"],
    )
    train_data_loader = torch.utils.data.DataLoader(
        train_dataset,
        pin_memory=True,
        num_workers=0,
        batch_size=params["batch_size"],
    )

    # Validation data
    print("Loading validation data...")
    print(params["validation_chroms"])
    val = extract_loci(
        loci=params["validation_loci"],
        sequences=params["sequences"],
        signals=params["signals"],
        in_signals=params["controls"],
        chroms=params["validation_chroms"],
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=0,
        ignore=list("QWERYUIOPSDFHJKLZXVBNM"),
        verbose=params["verbose"],
    )
    if len(val) == 3:
        X_valid, y_valid, X_ctl_valid = val
        X_ctl_valid = torch.abs(X_ctl_valid)
    else:
        X_valid, y_valid = val
        X_ctl_valid = None
    y_valid = torch.abs(y_valid)

    # Initialize model and optimizer
    n_control_tracks = len(params["controls"]) if params["controls"] else 0
    model = BPNet(
        name=params["name"],
        n_filters=params["n_filters"],
        n_outputs=len(params["signals"]),
        n_control_tracks=n_control_tracks,
        count_loss_weight=params["alpha"],
        n_layers=params["n_layers"],
        trimming=(params["in_window"] - params["out_window"]) // 2,
        verbose=params["verbose"],
    )
    model = model.to("cuda")
    optimizer = AdamW(model.parameters(), lr=params["learning_rate"])

    # Fit model
    model.fit(
        training_data=train_data_loader,
        optimizer=optimizer,
        X_valid=X_valid,
        X_ctl_valid=X_ctl_valid,
        y_valid=y_valid,
        max_epochs=params["max_epochs"],
        batch_size=params["batch_size"],
        early_stopping=params["early_stopping"],
        dtype="float32",
    )

    print(f"\nModel saved to {output_dir}/")


if __name__ == "__main__":
    main()
