"""
Train a BPNet model for one experiment/fold.

Reads experiment paths from config/experiment_config.yaml and chromosome
splits from config/chrom_splits.yaml. Fold i holds out fold i for testing
and validates on fold (i+1) % n_folds. Remaining folds are used for training.

For species with too few chromosomes for chromosome-based CV (e.g. S. pombe),
random peak-based splits are used instead when a file matching
config/splits/{species}_random_fold_assignments.csv exists. That file is
generated by src/data_preprocessing/make_random_splits.py.

Usage:
    python src/bpnet/fit/fit_bpnet.py -e D.melanogaster-S2_PROcap -f 0
    python src/bpnet/fit/fit_bpnet.py -e S.cerevisiae_PROcap -f 0
    python src/bpnet/fit/fit_bpnet.py -e S.pombe_PROcap -f 0
"""

# Tracks kundajelab/procap-atlas's src/bpnet/fit/fit_bpnet.py, which is this
# repo's source of truth for io, sampling and training standards.

import argparse
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
from experiments import (  # noqa: E402
    IGNORE,
    Experiment,
    load_params,
    model_dir,
    model_name,
)


def load_bed(path: str | Path) -> pd.DataFrame:
    df = pd.read_csv(
        path,
        sep="\t",
        usecols=[0, 1, 2],
        header=None,
        index_col=False,
        names=["chrom", "start", "end"],
    )
    df["chrom"] = df["chrom"].astype(str)
    return df


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "-e",
        "--experiment",
        type=str,
        required=True,
        help="experiment ID as it appears in experiment_config.yaml",
    )
    parser.add_argument(
        "-f",
        "--fold",
        type=int,
        required=True,
        help="fold to hold out for testing (validation = (fold+1) %% n_folds)",
    )
    parser.add_argument(
        "--controls",
        action="store_true",
        help="train with sRNA-seq bias controls (requires pl_control/mn_control in "
        "experiment config); saves to a separate {experiment}_ctl model directory",
    )
    parser.add_argument("-o", "--output-dir", type=str, default=None)
    parser.add_argument("--n-filters", type=int, default=None)
    parser.add_argument("--n-layers", type=int, default=None)
    parser.add_argument(
        "--count-loss-weight", "--alpha", dest="count_loss_weight", type=float,
        default=None, help="weight on the count loss (upstream name for --alpha)",
    )
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--lr", type=float, default=None)
    parser.add_argument("--max-epochs", type=int, default=None)
    parser.add_argument("--early-stopping", type=int, default=None)
    parser.add_argument("--max-jitter", type=int, default=None)
    parser.add_argument("--random-state", type=int, default=None)
    parser.add_argument(
        "--no-ratio-cap", action="store_true",
        help="do not cap negatives_ratio at the available pool. The cap stops a "
             "negative being drawn more than once per epoch, but it also lowers "
             "the negative share of each batch (12.5%% -> ~1.3%% for the densest "
             "yeast experiment). Use this to keep the configured batch "
             "composition and accept the repeats",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    # Resolve the experiment: paths, species, exclusion list. Shared with every
    # other script in the repo via src/experiments.py.
    try:
        exp = Experiment.load(args.experiment, use_controls=args.controls)
    except (KeyError, ValueError) as err:
        print(f"Error: {err}", file=sys.stderr)
        sys.exit(1)
    if exp.missing:
        for m in exp.missing:
            print(f"Error: missing {m}", file=sys.stderr)
        sys.exit(1)

    # Folds: chromosome-level, or peak-level where the species has too few
    # chromosomes (S. pombe). Same rule everywhere: test = i, valid = (i+1) % n.
    if exp.species == "S.pombe" and not exp.uses_peak_level_splits:
        print(
            "Error: S. pombe requires peak-level splits. Generate "
            f"{exp.random_splits_path} with "
            "src/data_preprocessing/make_random_splits.py before training.",
            file=sys.stderr,
        )
        sys.exit(1)
    try:
        split = exp.fold_split(args.fold)
    except (KeyError, ValueError) as err:
        print(f"Error: {err}", file=sys.stderr)
        sys.exit(1)

    suffix = "_ctl" if args.controls else ""
    output_dir = Path(args.output_dir) if args.output_dir else model_dir(
        "bpnet", args.experiment, suffix
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    # Hyperparameters come from config/bpnet_params.json so that training and the
    # downstream benchmark/attribution scripts cannot disagree.
    params = load_params("bpnet", {
        "n_filters": args.n_filters,
        "n_layers": args.n_layers,
        "count_loss_weight": args.count_loss_weight,
        "batch_size": args.batch_size,
        "learning_rate": args.lr,
        "max_epochs": args.max_epochs,
        "early_stopping": args.early_stopping,
        "max_jitter": args.max_jitter,
        "random_state": args.random_state,
        "verbose": True if args.verbose else None,
    })
    params.update({
        "name": (
            str(Path(args.output_dir) / f"{args.experiment}.fold{args.fold}")
            if args.output_dir
            else model_name("bpnet", args.experiment, args.fold, suffix)
        ),
        "sequences": str(exp.sequences),
        "signals": [str(x) for x in exp.signals],
        "controls": [str(x) for x in exp.controls] if exp.controls else None,
        "loci": str(exp.peaks),
        "blacklist": exp.blacklist,
        "training_chroms": split["train_chroms"],
        "validation_chroms": split["valid_chroms"],
    })

    # Heavy imports deferred until after argparse and path validation, so
    # --help and missing-data errors stay instant on a login node.
    import torch
    from bpnetlite.bpnet import BPNet
    from tangermeme.io import extract_loci
    from torch.optim import AdamW

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from data_loader import PeakGenerator

    n_folds = split["n_folds"]
    test_fold, valid_fold = split["test_fold"], split["valid_fold"]
    train_folds, use_random_splits = split["train_folds"], split["peak_level"]
    fold_df = split["fold_table"]
    gc_negatives_path = str(exp.negatives)

    # Load peaks and negatives here so we can pre-filter by fold if needed
    peaks = load_bed(params["loci"])
    negatives = load_bed(gc_negatives_path)

    loci = exp.fold_loci(peaks, args.fold)
    params["training_loci"] = loci["train_loci"]
    params["validation_loci"] = loci["valid_loci"]
    params["training_chroms"] = loci["train_chroms"]
    params["validation_chroms"] = loci["valid_chroms"]

    cli_overrides = {
        "n_filters": args.n_filters,
        "n_layers": args.n_layers,
        "count_loss_weight": args.count_loss_weight,
        "batch_size": args.batch_size,
        "learning_rate": args.lr,
        "max_epochs": args.max_epochs,
        "early_stopping": args.early_stopping,
        "max_jitter": args.max_jitter,
        "random_state": args.random_state,
    }
    for k, v in cli_overrides.items():
        if v is not None:
            params[k] = v
    if args.verbose:
        params["verbose"] = True

    print(f"Experiment: {exp.id} ({exp.entry['biosample']}, {exp.species})")
    if use_random_splits:
        n_train = len(params["training_loci"])
        n_val = len(params["validation_loci"])
        n_test = loci["n_test"]
        print(
            f"Fold {args.fold} (random splits): train={n_train}, "
            f"val={n_val}, test={n_test} peaks"
        )
    else:
        print(f"Fold {args.fold}: test={split['test_chroms']}, valid={split['valid_chroms']}")

    # Cap negative_ratio at the pool actually available, so no negative is drawn
    # more than once per epoch. `negative_ratio` is negatives PER PEAK in a
    # batch, so an epoch over N peaks draws N * ratio; where the pool is smaller
    # than that the same regions recycle. That is not hypothetical -- with the
    # configured 1/7, `S.cerevisiae-Spt5IAA4h_PROcap` draws 3,377 from a pool of
    # 327, about 10x over, because its peaks are denser than one per training
    # window and almost no window is peak-free.
    #
    # Computed from the WHOLE-GENOME counts, not the fold's. PeakGenerator
    # filters both peaks and negatives by the same `chroms`, so pool/peaks is
    # near-constant across folds, and the exact per-fold counts are not knowable
    # here without duplicating extract_loci. An approximate cap that is always
    # in the right direction beats forking data_loader.py, which is
    # byte-identical to procap-atlas's.
    #
    # Only ever engages for the yeasts: every other experiment's pool is at
    # least 0.26 per peak, comfortably above 1/7.
    # NOTE this addresses RECYCLING, not DIVERSITY, and they are orthogonal: the
    # pool is the same N distinct windows whichever ratio is used. Capping only
    # lowers how often each is seen, which also lowers the negative share of a
    # batch -- 12.5% to about 1.3% for Spt5IAA4h. If the negative class's batch
    # weight matters more than avoiding repeats, pass --no-ratio-cap.
    configured_ratio = params["negatives_ratio"]
    available_ratio = len(negatives) / max(len(peaks), 1)
    if args.no_ratio_cap:
        available_ratio = configured_ratio
    if available_ratio < configured_ratio:
        params["negatives_ratio"] = available_ratio
        print(
            f"negative_ratio capped {configured_ratio:.4f} -> {available_ratio:.4f}: "
            f"{len(negatives):,} negatives for {len(peaks):,} peaks, so the "
            f"configured ratio would recycle each negative "
            f"{configured_ratio / available_ratio:.1f}x per epoch"
        )

    # Training DataLoader. Delegated to data_loader.PeakGenerator (identical to
    # procap-atlas's) rather than reimplemented here: it already applies the
    # torch.abs() minus-strand handling, the 99th-percentile outlier filter, and
    # the peak/negative interleaving. Keeping one copy avoids the two drifting.
    print(f"Loading training data (chroms: {params['training_chroms']})...")
    train_data_loader = PeakGenerator(
        peaks=params["training_loci"],
        negatives=negatives,
        sequences=params["sequences"],
        signals=params["signals"],
        controls=params["controls"],
        chroms=params["training_chroms"],
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=params["max_jitter"],
        reverse_complement=params["reverse_complement"],
        shuffle=params["shuffle"],
        random_state=params["random_state"],
        batch_size=params["batch_size"],
        verbose=params["verbose"],
        negative_ratio=params["negatives_ratio"],
        exclusion_lists=params["blacklist"],
        min_counts=None,
        max_counts=None,
        pin_memory=True,
        num_workers=0,
    )

    # Validation data
    print("Loading validation data...")
    print(params["validation_chroms"])
    val = extract_loci(
        loci=params["validation_loci"],
        sequences=params["sequences"],
        signals=params["signals"],
        in_signals=params["controls"],
        chroms=params["validation_chroms"],
        in_window=params["in_window"],
        out_window=params["out_window"],
        max_jitter=0,
        ignore=IGNORE,
        exclusion_lists=params["blacklist"],
        verbose=params["verbose"],
    )
    if len(val) == 3:
        X_valid, y_valid, X_ctl_valid = val
        X_ctl_valid = torch.abs(X_ctl_valid)
    else:
        X_valid, y_valid = val
        X_ctl_valid = None
    y_valid = torch.abs(y_valid)

    # Initialize model and optimizer
    n_control_tracks = len(params["controls"]) if params["controls"] else 0
    model = BPNet(
        name=params["name"],
        n_filters=params["n_filters"],
        n_outputs=len(params["signals"]),
        n_control_tracks=n_control_tracks,
        count_loss_weight=params["count_loss_weight"],
        n_layers=params["n_layers"],
        trimming=(params["in_window"] - params["out_window"]) // 2,
        verbose=params["verbose"],
    )
    model = model.to("cuda")
    optimizer = AdamW(model.parameters(), lr=params["learning_rate"])

    # Fit model
    model.fit(
        training_data=train_data_loader,
        optimizer=optimizer,
        X_valid=X_valid,
        X_ctl_valid=X_ctl_valid,
        y_valid=y_valid,
        max_epochs=params["max_epochs"],
        batch_size=params["batch_size"],
        early_stopping=params["early_stopping"],
        dtype=torch.float,
    )

    print(f"\nModel saved to {output_dir}/")


if __name__ == "__main__":
    main()
